### PR TITLE
Dev getting far ahead of Master

### PR DESCRIPTION
**Pull request by wilddeej**
Dev is in a pretty stable and functional state right now.  Wouldn't this be a good point to sync it with Master?

### CODE REVIEW

**Comment by aurelg** [comment]
Indeed. Before that, I'm going to test the dev branch during the coming days.

**Comment by aurelg** [comment]
I notice the `dev` branch doesn't pass the `pytest` tests:

```
============================= test session starts ==============================
platform linux -- Python 3.6.7, pytest-4.0.0, py-1.7.0, pluggy-0.8.0
rootdir: /home/aurelien/workspace/feedspora, inifile:
collected 6 items

tests/client_test.py .F....                                              [100%]

=================================== FAILURES ===================================
______________________________ test_TweepyClient _______________________________

entry_generator = <generator object FeedSpora.parse_atom at 0x7fca1ae2f468>
expected = [{'source': {'keywords': ['vegetable', 'mineral', 'animal'], 'link': 'http://example.org/2003/12/13/atom03', 'title': ...atement.on Potentially Unlawful Promotion of Initial Coin Offerings and Other Investments by Celebrities and Others'}}]

    def test_TweepyClient(entry_generator, expected):
        def new_init(obj):
            class fake_provider():
                def update_status(self, text):
                    return {'text': text}
    
            obj._api = fake_provider()
            obj._link_cost = 22
            obj._max_len = 280
    
        def check_entry(returned, expected):
            assert returned['text'].startswith(expected['title'])
            assert returned['text'].endswith(expected['link'])
            # Check the length of the text - link + 22 (twitter cost)
            returned_text = returned['text'][:returned['text'].rfind(' ')]
            putative_urls = re.findall(r'[a-zA-Z0-9]+\.[a-zA-Z]{2,3}',
                                       returned_text)
            # Infer the 'inner links' Twitter may charge length for
            adjust_with_inner_links = 0
    
            if len(putative_urls) > 0:
                adjust_with_inner_links = sum([22 - len(u) for u in putative_urls])
            detected_length = len(returned_text) + 22 + adjust_with_inner_links
            assert not detected_length > 280
    
            for k in expected['keywords']:
                target = ' #{}'.format(k)
                assert returned['text'].index(target) > -1
    
        TweepyClient.__init__ = new_init
>       check(TweepyClient(), entry_generator, expected, check_entry)

tests/client_test.py:112: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
tests/client_test.py:53: in check
    check_entry(returned, expect[expect_key])
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

returned = {'text': '1.1 - Mort numérique: que faire des données personnelles et des comptes Facebook après un décès ? - Le blog ...allatavocat.com/2017/10/mort-numerique-que-faire-des-donnees-personnelles-et-des-comptes-facebook-apres-un-deces.html'}
expected = {'keywords': [], 'link': 'http://www.thierryvallatavocat.com/2017/10/mort-numerique-que-faire-des-donnees-personnelles...s Facebook après un décès ? - Le blog de Thierry Vallat, avocat au Barreau de Paris (et sur Twitter: MeThierryVallat)'}

    def check_entry(returned, expected):
>       assert returned['text'].startswith(expected['title'])
E       AssertionError: assert False
E        +  where False = <built-in method startswith of str object at 0x7fca1b9d5a70>('1.1 - Mort numérique: que faire des données personnelles et des comptes Facebook après un décès ? - Le blog de Thierry Vallat, avocat au Barreau de Paris (et sur Twitter: MeThierryVallat)')
E        +    where <built-in method startswith of str object at 0x7fca1b9d5a70> = '1.1 - Mort numérique: que faire des données personnelles et des comptes Facebook après un décès ? - Le blog de... htt...vallatavocat.com/2017/10/mort-numerique-que-faire-des-donnees-personnelles-et-des-comptes-facebook-apres-un-deces.html'.startswith

tests/client_test.py:93: AssertionError
---------------------------- Captured stderr setup -----------------------------
INFO:root:Trying to read tests/feed.atom as a file.
INFO:root:Feed read.
------------------------------ Captured log setup ------------------------------
feedspora_runner.py        897 INFO     Trying to read tests/feed.atom as a file.
feedspora_runner.py        909 INFO     Feed read.
====================== 1 failed, 5 passed in 0.52 seconds ======================
```

It's certainly something we need to fix/explain before the merge.

**Comment by wilddeej** [comment]
There was a change in the Tweepy implementation to make sure that the post link didn't get omitted from the tweet.  You can see in the "expected" post that there is no link included, but there is in the "returned" link.  As the "returned" string is actually more correct, I think this just means the test needs to be updated.
I'd be happy to take care of that, as long as you agree with my analysis above.

**Comment by aurelg** [comment]
I checked quickly and it seems you nailed it (and got the right to fix it) :-)

**Comment by wilddeej** [comment]
My original plan was to modify the test data so the test would pass, but that seemed a bit "hacky" so I instead set out to change the test logic instead.  That has turned out to be much more complicated than I thought it would be (even to figure out the proper place to slice the title string), since there is a lot of logic going on in the mkrichtext string formatting function.  Would it be considered "legal" to call that function rather than trying to emulate its logic?

**Pull request merged**
