### PR TITLE
Allow update/repost of already-published items

### PR DESCRIPTION
**Pull request by wilddeej**
If an item's information includes the date upon which it was published, this information
is used as part of the "published" database entry, along with the relevant link.  This
allows an item with the same link to be published again later, as long as its published
date is different.  For those items containing no publication date, the former behavior
is unchanged.
Only the RSS feed implementation for this feature is in place at this point, but it would
be trivial to implement this functionality for Atom feeds as well.

### CODE REVIEW

**Comment by aurelg** [comment]
Thanks for this new PR.

I had a deeper look at your previous ones, and noticed a few issues:

- tests should be improved:
    - the unnecessary bracketing with `()` in `if` statements (and tests in general) should be removed
    - `var is not None` should be just `var`
- multiple return statements should be avoided as they make the execution flow harder to follow
- logging should be lazy
- several docstrings are missing

My own code was not much better, fortunately I started to use `yapf`, `pylint` and `flake8` in my editor since I worked on this project. You might want to give them a try as well.

I tried to fix most of them in a new `dev` branch. I'm going to check that it works in the coming days. Unfortunately, I'm using python 3.7 and [cannot test Tweepy](https://github.com/tweepy/tweepy/issues/1063). Can you check that this `dev`  branch is working as expected (especially the connection to Twitter)?

Once we are confident that this `dev` branch is reliable enough, I'll merge this new PR and merge it with `master`.

PS: BTW, In this PR, I see additional issues with the formatting of `try... except...` blocks.

**Comment by aurelg** [comment]
- about lazy logging, see "Manual Interpolation" [here](https://www.simonmweber.com/2014/11/24/python-logging-traps.html)
- about the missing docstring: you can use the linters I mentioned to find out the ones that are still missing, if any (maybe they were missing from functions I wrote, not in yours :-/)
- about the `try... catch...` block: `hasattr`  should do the trick:
```
if not hasattr(entry, 'published_date'):
    entry.published_date = None
```

BTW, a better solution would be to add `published_date` directly in `FeedSporaEntry`, so that this field is available in other Clients as well. It's important to implement it both in RSS and Atom.

Finally, it would make sense to put PR against `dev`, yes :-)

**Comment by aurelg** [comment]
BTW, I also noticed that in order to keep the order of the keywords in TweepyClient, you:

- create a list `all_keywords` ([here](https://github.com/aurelg/feedspora/pull/11/files#diff-2b8f6cc3c6d506f4d82ca5300777098fR266)),
- pass the `all_keywords` to `mkrichtext` ([here](https://github.com/aurelg/feedspora/pull/13/files#diff-2b8f6cc3c6d506f4d82ca5300777098fR365))
- change the type of keywords from `set` to `list` ([here](https://github.com/aurelg/feedspora/pull/13/files#diff-2b8f6cc3c6d506f4d82ca5300777098fL100)),

The combination of the changes created the hashtag duplication bug you had to fix later, and I just realized it also broke the other clients I am using: inline keywords were not prefixed with a `#` anymore. `mkrichtext` is expecting a set: you cannot just change the parameter type and expect a correct behavior. It's important to be super careful when you change functions that are shared between clients, especially when there's no specific test for this part of the code.

Should you want to keep the order of keywords, you must find another way to do it. BTW, AFAIK, the order of keywords (categories, per se) in Atom and RSS has no particular meaning and unless you have a strong argument in favor of keeping the original order, I will revert your changes.

When I started this project, I had little time to write tests. If we want to work on it at the same time, tests with a proper coverage should be added prior to adding new features, otherwise we'll break everything and end up with an unusable mess.

**Comment by wilddeej** [comment]
Sorry about that.  I certainly didn't mean to break anything.
I DO think that the order of tags is (or at least should be allowed to be)
significant.  In my particular use case, the content often contains around
a dozen hashtags (which is how the all_keywords list gets generated), and
the ones at the beginning of the list have more "value" than those at the
end of the list.  This is even more true when the number of tags is limited
(using the new max_tags) - I think it's more useful to know you're limiting
to the "first four tags" rather than "four random tags".
I think this is also pertinent to another one of the clients that I notice
has a "keywords" option.  That seems really nice, but it seems like this
will randomly fail if you implement max_tags for that client; with a set
implementation there will be no guarantee that the specified keywords will
in fact end up in the post, again, when using this with max_tags.

**Comment by aurelg** [comment]
I checked the [Atom](https://tools.ietf.org/html/rfc4287) and [RSS](http://www.rssboard.org/rss-specification) specification and found nothing WRT the order of categories. I understand it's left up to the feed provider to decide whether the order is relevant or not, and we can't assume that it's relevant or that it's not (even though I would personally like if it were). That being said, I agree it makes sense not to alter the order of the categories/keywords. We just must be sure that the corresponding implementation does not break the code. NP for the side effect, I should have been more rigorous while looking at your commit. It's time to write tests. :-)

**Comment by wilddeej** [comment]
Would it be OK to add items to the tests/feed.rss file, or should I use
some other mechanism?  Maybe we should even start a feed.rss directory with
multiple test case files...

**Comment by aurelg** [comment]
Sure, `feed.rss` and `feed.atom` can be modified. The coverage of functional tests is way less thorough than that of unit tests, especially of edge cases, but that's better than nothing.

**Pull request closed without merging**
